### 0.numpy导包和查看版本命令

In [1]:
import numpy as np
print(np.__version__)

1.26.2


### 1.数组
#### 1.1 array(object)
> array(object,dtype=None, copy=True, order=‘K’, subok=False, ndmin=0)
- object : **可迭代对象**(判断对象是否可迭代:collections库isinstance方法)
- dtype : 数据类型
- copy : bool值,表示是否复制!此处引用到数组的复制!
- order : 元素在内存中出现的顺序,可以是"K""A""F""C",
    - "K”,表示元素在内存中出现的顺序。
    - “C”表示按行优先(row-major)
    - “F”表示按列优先。
    - 如果object是一个数组，则还可以是"A”，表示原顺序。
- subok : bool值,表示返回的数组默认为**基类数组**。如果为True则将传递子类
- ndmin : 生成数组的**最小维度**(不足则补充)

##### 1.1.1 列表创建
如下图,分别创建出了一维、二维、三维数组，并打印出了其shape。

In [2]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1,a1.shape)

a2 = np.array([1, 2, 3, 4, 5], ndmin=2)
print(a2, a2.shape)

a3 = np.array([1, 2, 3, 4, 5], ndmin=3)
print(a3, a3.shape)

[1 2 3 4 5] (5,)
[[1 2 3 4 5]] (1, 5)
[[[1 2 3 4 5]]] (1, 1, 5)


##### 1.1.2 通过元组创建

In [3]:
a2 = np.array((1.,2.,3.,4.,5.))
print(a2)

[1. 2. 3. 4. 5.]


##### 1.1.3 通过字符串创建

In [4]:
a3=np.array('123')
print(a3,type(a3))

123 <class 'numpy.ndarray'>


##### 1.1.4 通过数组创建

In [5]:
n1=np.array(a1)
print(n1)
n2=np.array([a1,a2]) #发生类型转换
n3=np.array(n2)
print(n3)

[1 2 3 4 5]
[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


##### 1.1.5 数组的复制
当我们需要修改数组又不想影响到目标数组时,通常可以通过"用数组创建数组",进而实现对目标数组的复制操作。<br/>
下例是不复制的情形(n1和n2共用储存):

In [6]:
n1 = np.array([1, 2, 3])
n2 = np.array(n1)
n1 = np.array([1, 2, 3])
n2 = np.array(n1, copy=False)
print("n1:", n1)
print("n2:", n2)
print("n1和n2的序列号是否相同:",n1 is n2)
n2[0] =100
print("**********修改n2的第一个数据***********")
print("n1:", n1)
print("n2:", n2)

n1: [1 2 3]
n2: [1 2 3]
n1和n2的序列号是否相同: True
**********修改n2的第一个数据***********
n1: [100   2   3]
n2: [100   2   3]


##### 1.1.6 通过range创建

In [7]:
a1 = np.array(list(range(10)))
print(a1)

[0 1 2 3 4 5 6 7 8 9]


#### 1.2 arange()方法
arrange是numpy对range优化过后的方法，常用来创建数组。而通常不再采用上边的range()方法。
> arange(start,stop,step,dtype=None)
- 取值方式为**左开右闭**
- 结果可以是整型

In [15]:
a1 = np.arange(0, 10, 2)
print(a1)
a1 = np.arange(0, 9, 2)
print(a1)
a1 = np.arange(0, 11, 2)
print(a1)
a1 = np.arange(0, 11, 2.1)
print(a3)

[0 2 4 6 8]
[0 2 4 6 8]
[ 0  2  4  6  8 10]
[ 0.   2.1  4.2  6.3  8.4 10.5]


#### 1.3 linspace()(等差),logspace()(等比)
> linspace(start, stop, num=50, end_point=True, restep=False, dtype=None)
- endpoint : bool值,默认为True,表示包含stop
- restep bool值,默认为True,表示生成的数组显示间距
- 无论结果是否是整数，都默认为是浮点型
> logspace(start, stop, num=50, end_point=True, base=10.0, dtype=None)
- 序列的起始值为 $base^{start}$ ,结束值为 $base^{stop}$

In [32]:
n1 = np.linspace(100, 200, 11)
print(n1)
n1 = np.logspace(0, 10, 6, base=2, dtype='int')
print(n1)

[100. 110. 120. 130. 140. 150. 160. 170. 180. 190. 200.]
[   1    4   16   64  256 1024]


#### 1.5 empty()与ones()
> numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)<br/>
> numpy.ones(shape, dtype=None, order='C', *, device=None, like=None)<br/>
> numpy.zeros(shape, dtype=float, order='C', *, like=None)<br/>
> numpy.full(shape, fill_value, dtype=None, order='C', *, device=None, like=None)<br/>
> numpy.shape(a)<br/>

- ```shape```返回整数元组,```empty```构造全空数组,```ones```构造全1数组,```zeros```
> ```device``` : 在哪里创建数组,仅针对Array-API互操作性,因此如果通过,则必须为“cpu”.<br/>
> ```like``` : 
引用对象，以允许创建不是NumPy数组的,组。如果像这样传入的数组支持__array_function__议，则结果将由其.义。在这种情,下，它确保创建与通过此参数传入的数组对象兼容的数组.象。

In [38]:
a = np.array([(1, 2), (3, 4), (5, 6)], dtype=[('x', 'i4'), ('y', 'i4')])
print(a.shape)
print("======================================================================")
n1 = np.empty([2, 3])
print(n1)
print("======================================================================")
n2 = np.empty([2, 3], dtype=int)
print(n2)

(3,)
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
[[1 2 3]
 [4 5 6]]


### 2.常数

In [31]:
print(np.e,np.euler_gamma,np.pi,np.newaxis,np.nan,np.inf)

2.718281828459045 0.5772156649015329 3.141592653589793 None nan inf
